name: Build
on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: string

jobs:
  build:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm ci

    - name: Build
      env:
        NODE_ENV: ${{ inputs.environment }}
        VITE_SUPABASE_URL: ${{ vars.SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ vars.SUPABASE_ANON_KEY }}
        VITE_API_BASE_URL: ${{ vars.API_BASE_URL }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      run: npm run build

    - name: Upload compiled website
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ./dist/
        if-no-files-found: error
