name: '[Production] Deploy'
on:
  push:
    tags:
      - 'v**'
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: production
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: production

  deploy:
    needs: build
    environment: production
    runs-on: ubuntu-latest

    steps:
    - name: Download compiled website
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: 0f20863ce606a851a24e64d30dc8ec9c
        projectName: 'reserve-ja-admin'
        directory: dist